l[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=2.14.0",
    "psycopg2-binary>=2.9.11",
    "pypdf>=6.5.0",
    "streamlit>=1.52.2",
]
